#ifndef _FILESYSTM_CONSTANT_NAMESPACEPARAM_H_
#define _FILESYSTM_CONSTANT_NAMESPACEPARAM_H_

#define OPERATE_SECCESS 999
//文件名不合法
#define ILEGAL_FILE_NAME 1000
//文件名已存在
#define FILE_EXISTS 1001
#define FILE_NOT_EXISTS 1001
//目录名不合法
#define ILLEGAL_DIR_NAME 1002
//目录已经存在
#define DIR_EXISTS 1003
//目录不存在
#define DIR_NOT_EXISTS 1004
//illegal file pathILLEGAL_DIR_NAMETH
#define ILLEGAL_FILE_PATH 1005
//路径非法
#define ILLEGAL_PATH 1005
#define NOT_THE_SAME_DIR 1000
//创建成功
#define CREATE_SUCCESS 2000

#define NO_ENOUGH_SPACE -1

#endif
